---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dotnetcore-prometheus-example'
    # metrics_path defaults to '/metrics'
    static_configs:
      - targets: ['localhost:5000']
